convostarters = ["What three words best describe you",
"What would be your perfect weekend?",
"What’s your favorite way to waste time?",
"What is something popular now that annoys you?",
"If you were stranded on a deserted island, what 2 things would you want to bring with you? They can not be transportation related.",
"What is the greatest lesson in life you have ever learned?",
"Are you very active, or do you prefer to just relax in your free time?",
"If you opened a business, what kind of business would it be?",
"What is the strangest dream you have ever had?",
"How long do you spend looking at a computer screen every day?",
"What’s your favorite season? Why?",
"Which is more important, having a great car or a great house? Why?",
"How much time do you spend on the internet? What do you usually do?",
"What is the most disgusting habit some people have?",
"Where is the worst place you have been stuck for a long time?",
"If you had to change your name, what would your new name be?",
"What word or saying from the past do you think should come back?",
"What is your guilty pleasure?",
"Was there ever an event in your life that defied explanation?"]